### ISSUE TITLE
Request TRX for testing does not add the TRX for first time login

### ISSUE THREAD

**Issue by martono91** [tronprotocol/java-tron#581]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Request TRX for testing does not add the TRX for first time login

2. What did you expect to see?
TRX token should increase by 10,000 k for first time request

3. What did you see instead?
0 Balance

**Comment by Rovak** [comment]
There were temporary problems with the network, should be solved now

**Comment by haidoan** [comment]
hi @Rovak , I still get this issue when request TRX for testing, please help, thanks

**Comment by wuno** [comment]
I have seen that the ability to request TRX has been removed from the account page on https://test.tronscan.org/#/account

Does anyone know how we are supposed to obtain test TRX?

**Comment by haidoan** [comment]
@wuno I also cant find test TRX so I have test with mainnet TRX, You can get 2 main net TRX from [here](https://t.me/TronHelp). this issue existing for long time but seem like tron foundation ignore it.
